[package]
name = "soroban-escrow-contract"
version = "0.1.0"
edition = "2021"
description = "Milestone-based Escrow contract for the Stellar Freelance Escrow Marketplace"

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
ed25519-dalek = { workspace = true }
soroban-job-registry-contract = { path = "../job_registry" }
soroban-reputation-contract = { path = "../reputation" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testutils = ["soroban-sdk/testutils"]
